name: Deploy to Github Pages
  on:
    push:
      branches:
        - develop
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '12'
          - name: Install packages
            run: npm i
          - name: Set Creds
            run: git config user.name "eudisley" && git config user.email "eudisley@gmail.com"
          - name: Deploy
            run: npm run gh-pages-deploy
          - name: Change branch
            run: git checkout gh-pages
#           - name: Create CNAME
#             run: echo "interop.gsmainclusivetechlab.io" > CNAME
          - name: Create 404
            run: cp index.html 404.html
          - name: Push new files
            run: git add 404.html && git commit -m "Update CNAME" && git push
#             run: git add CNAME 404.html && git commit -m "Update CNAME" && git push
